config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope module: :public do#顧客・会員
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/confirm' => 'customers#confirm', as: 'confirm'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    post '/cart_item/:id' => 'cart_items#update', as: 'cart_item'
    delete '/cart_item/:id' => 'cart_items#destroy', as: 'destroy_cart_item'
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :confirm, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }




  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { before: 0, confirm: 1, making: 2, before_sending: 3, sent: 4 }
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {before: 0, waiting: 1, making: 2, finish: 3}

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :telephone_number, :postal_code, :email, :is_deleted)
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).per(10)
    @total = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

   private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order_detail = OrderDetail.find(params[:id])
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    # @order_details = OrderDetail.where(order_id: @order.id)
    # if @order.update(order_params)
    #   @ordered.order_details.update_all(production_status: 1) if @order.order_status == 1
    # end
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end


  private
   def order_params
     params.require(:order).permit(:order_status)
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protect_from_forgery



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end


end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active px-4 mt-4"><%= @customer.last_name %><%= @customer.first_name %>
    さんの会員情報編集</h4>
  </div>

<%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
    <div class="row mt-4">
      <div class="col-2"><p>会員ID</p></div>
      <div class="col"><%= @customer.id %></div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= f.label :氏名 %>
      </div>
      <div class="col-2 mr-5">
        <%= f.text_field :last_name %>
      </div>
      <div class="col">
        <%= f.text_field :first_name %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-2">
        <%= f.label :フリガナ %>
      </div>
      <div class="col-2 mr-5">
        <%= f.text_field :last_name_kana %>
      </div>
      <div class="col">
        <%= f.text_field :first_name_kana %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-2">
        <%= f.label :郵便番号 %>
      </div>
      <div class="col">
        <%= f.text_field :postal_code %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-2">
        <%= f.label :住所 %>
      </div>
      <div class="col">
        <%= f.text_field :address %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-2">
        <%= f.label :電話番号 %>
      </div>
      <div class="col">
        <%= f.text_field :telephone_number %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-2">
        <%= f.label :メールアドレス %>
      </div>
      <div class="col">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="row mt-2">
        <%= form_with(model: @customer, local: true) do |form| %>
      <div class="col-2">
         <%= form.label :会員ステータス %>
      </div>
      <div class="col-1">
        <%= form.radio_button :is_deleted, false %>
        <%= form.label :is_deleted, '有効', value: false %>
      </div>
      <div class="col">
        <%= form.radio_button :is_deleted, true %>
        <%= form.label :is_deleted, '退会', value: true %>
      </div>
        <% end %>
    </div>

    <div class="row">
      <div class="col-2"></div>
      <div class="col">
        <%= f.submit "変更を保存", class:"btn btn-success btn-lg mt-4" %>
      </div>
    </div>

  </div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active ml-5 mt-4 px-4">会員一覧</h4>
  </div>

  <div class="row">
    <div class="col-9 mt-3 mx-auto">
<table class="table">
  <thead class="table-active">
    <tr>
      <th class="col-2">会員ID</th>
      <th class="col-3"><u>氏名</u></th>
      <th class="col-4">メールアドレス</th>
      <th class="col-3">ステータス</th>
    </tr>
  </thead>
  <% @customers.each do |customer| %>
  <tbody>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to admin_customer_path(customer.id) do %>
            <u class="text-dark">
              <%= customer.last_name %><%= customer.first_name %>
            </u>
          <% end %>
      </td>
      <td><%= customer.email %></td>
        <% if customer.is_deleted == true %>
          <td class="align-middle font-weight-bold text-secondary">退会</td>
        <% elsif customer.is_deleted == false %>
          <td class="align-middle font-weight-bold text-success">有効</td>
        <% end %>

    </tr>
  </tbody>
  <% end %>
</table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active px-4 mt-4"><%= @customer.last_name %><%= @customer.first_name %>
    さんの会員詳細</h4>
  </div>


  <div class="row mt-4">
    <div class="col-2"><p>会員ID</p></div>
    <div class="col"><%= @customer.id %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>氏名</p></div>
    <div class="col"><%= @customer.last_name %> <%= @customer.first_name %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>フリガナ</p></div>
    <div class="col"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>郵便番号</p></div>
    <div class="col"><%= @customer.postal_code %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>住所</p></div>
    <div class="col"><%= @customer.address %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>電話番号</p></div>
    <div class="col"><%= @customer.telephone_number %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>メールアドレス</p></div>
    <div class="col"><%= @customer.email %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><p>会員ステータス</p></div>
    <div class="col"><% if @customer.is_deleted == true %>
                       <p class="font-weight-bold text-secondary">退会</p>
                     <% elsif @customer.is_deleted == false %>
                       <p class="font-weight-bold text-success">有効</p>
                     <% end %>
    </div>
  </div>
  <div class="row mt-1">
    <div class="col-2"></div>
    <div class="col">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success mr-5 px-4" %>
      <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>
    </div>

  </div>
</div>