config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope module: :public do#顧客・会員
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/confirm' => 'customers#confirm', as: 'confirm'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    post '/cart_item/:id' => 'cart_items#update', as: 'cart_item'
    delete '/cart_item/:id' => 'cart_items#destroy', as: 'destroy_cart_item'
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :confirm, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }




  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { before: 0, confirm: 1, making: 2, before_sending: 3, sent: 4 }
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {before: 0, waiting: 1, making: 2, finish: 3}

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).per(10)
    @total = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

   private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order_detail = OrderDetail.find(params[:id])
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    # @order_details = OrderDetail.where(order_id: @order.id)
    # if @order.update(order_params)
    #   @ordered.order_details.update_all(production_status: 1) if @order.order_status == 1
    # end
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end


  private
   def order_params
     params.require(:order).permit(:order_status)
   end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protect_from_forgery



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end


end

app/views/admin/genres/edit.html.erb
<div class="container-flued">
  <div class="row">
    <div class="col-1"></div>
      <h4 class="table-active px-4 ml-5 mt-4">ジャンル編集</h4>
  </div>

<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
  <div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-1 mr-2">
      <%= f.label :ジャンル名 %>
    </div>
    <div class="col-2 mr-3">
      <%= f.text_field :name, class:"w-100" %>
    </div>
    <div class="col-2">
      <%= f.submit '変更を保存', class:"btn btn-success px-4 ml-3" %>
    </div>
<% end %>
</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-flued">
  <div class="row">
    <div class="col-1"></div>
      <h4 class="table-active px-4 ml-5 mt-4">ジャンル一覧・追加</h4>
  </div>

<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
  <div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-1 mr-2">
      <%= f.label :ジャンル名 %>
    </div>
    <div class="col-2 mr-3">
      <%= f.text_field :name, class:"w-100" %>
    </div>
    <div class="col-2">
      <%= f.submit '新規登録', class:"btn btn-success px-4 ml-3" %>
    </div>
  </div>
<% end %>


<div class="row mt-5">
  <div class="col-1"></div>
  <div class="col-3">
<table class="table">
  <thead>
    <tr class="table-active">
      <th class="pl-5">ジャンル</th>
      <th></th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <tr>
      <td class="col-7 align-middle"><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:'btn btn-success px-3' %></td>
    </tr>
  </tbody>
  <% end %>
</table>
  </div>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active px-4 ml-5 mt-4">商品編集</h4>
  </div>

<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

<div class="col-9 mx-auto">
  <div class="row ml-3 mt-4">
    <div class="col-3">
       <%= f.label :商品画像 %>
    </div>
    <div class="form-group">
      <div class="field">
       <%= f.file_field :image, accept: "image/*" %>
      </div>
    </div>
  </div>



  <div class="row ml-3">
    <div class="col-3">
      <%= f.label :商品名 %>
    </div>
      <%= f.text_field :name, class:"w-50" %>
  </div>
  <div class="row ml-3 mt-3">
    <div class="col-3">
      <%= f.label :商品説明 %>
    </div>
      <%= f.text_area :introduction, class:"w-50 form-control border-dark", size:"20x10" %>
  </div>

  <div class="row mt-3">　　<!--セレクトボックス-->
     <div class="col-2">
       <%= f.label :ジャンル %>
     </div>

   <div class="col-8">
     <%= f.select :genre_id, @genres.map{ |f| [f.name, f.id]}, { include_blank: '--選択してください--'}, class:"w-75 p-1 ml-5" %>
   </div>

      <!--genre_idに右のidの値が送られる-->
      <!--mapはeach文と同じように繰り返す-->
  </div>

  <div class="row ml-3 mt-3">
    <div class="col-3">
      <%= f.label :税抜価格 %>
    </div>
      <%= f.text_field :price, class:"w-50" %>円
  </div>

  <div class="row ml-3 mt-3">
  <%= form_with(model: @item, local: true) do |form| %>
    <div class="col-3">
      <%= form.label :販売ステータス %>
    </div>

    <div class="col-2">
      <%= form.radio_button :is_active, true %>
      <%= form.label :is_active, '販売中', value: true %>
    </div>

    <div class="col-2">
      <%= form.radio_button :is_active, false %>
      <%= form.label :is_active, '販売停止中', value: false %>
    </div>

<% end %>
</div>

<div class="row mt-4">
  <div class="col-5"></div>
  <div class="col-3">
    <%= f.submit "変更を保存", class:"btn btn-success btn-lg" %>
  </div>
</div>



</div>
  </div>
<% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 px-5"><h4 class="table-active ml-5 mt-4 text-center">商品一覧</h4></div>
    <div class="col-7"></div>
    <div class="col-2 pt-3">
      <%= link_to new_admin_item_path, class:'text-secondary' do %><i class="fa fa-plus-circle fa-3x"></i><% end %>
    </div>
  </div>

<table class="table table-borderless mt-4">
  <thead class="thead-light">
    <tr>
      <th class="align-middle col-1">商品ID</th>
      <th class="align-middle col-4">商品名</th>
      <th class="align-middle col-1">税抜価格</th>
      <th class="align-middle col-4">ジャンル</th>
      <th class="align-middle col-2">ステータス</th>
    </tr>
  </thead>
  <% @items.each do |item| %>
  <tbody>
    <tr>
      <td class="align-middle"><%= item.id %></td>
      <td class="align-middle"><%= link_to admin_item_path(item.id) do %><u class="text-dark"><%= item.name %></u><% end %></td>
      <td class="align-middle"><%= item.price.to_s(:delimited) %></td>
      <td class="align-middle"><%= item.genre.name %></td>

        <% if item.is_active == true %>
          <td class="align-middle font-weight-bold text-success">販売中</td>
        <% elsif item.is_active == false %>
          <td class="font-weight-bold text-secondary">販売停止中</td>
        <% end %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
<div class="row">
  <div class="mx-auto">
    <%= paginate @items %>
  </div>
</div>
</div>
</html>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active px-4 ml-5 mt-4">商品新規登録</h4>
  </div>

<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>


<div class="col-9 mx-auto">
  <div class="row ml-3 mt-4">
    <div class="col-3">
      <%= f.label :商品画像 %>
    </div>

      <div class="form-group">
        <div class="field">
            <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>
  </div>
  <div class="row ml-3">
    <div class="col-3">
      <%= f.label :商品名 %>
    </div>
    <%= f.text_field :name, class:"w-50" %>
  </div>
  <div class="row ml-3 mt-3">
    <div class="col-3">
      <%= f.label :商品説明 %>
    </div>
    <%= f.text_area :introduction, class:"w-50 form-control border-dark", size:"20x10" %>
  </div>
  <div class="row mt-3">　　<!--セレクトボックス-->
     <div class="col-2">
       <%= f.label :ジャンル %>
     </div>

   <div class="col-8">
     <%= f.select :genre_id, @genres.map{ |f| [f.name, f.id]}, { include_blank: '--選択してください--'}, class:"w-75 p-1 ml-5" %>
   </div>

      <!--genre_idに右のidの値が送られる-->
      <!--mapはeach文と同じように繰り返す-->
  </div>

  <div class="row ml-3 mt-3">
    <div class="col-3">
      <%= f.label :税抜価格 %>
    </div>
    <%= f.text_field :price, class:"w-50" %>円
  </div>

  <div class="row ml-3 mt-3">
  <%= form_with(model: @item, local: true) do |form| %>
    <div class="col-3">
      <%= form.label :販売ステータス %>
    </div>

     <div class="col-2">
      <%= form.radio_button :is_active, true %>
      <%= form.label :is_active, '販売中', value: true %>
     </div>

     <div class="col-2">
      <%= form.radio_button :is_active, false %>
      <%= form.label :is_active, '販売停止中', value: false %>
     </div>

<% end %>
</div>

<div class="row mt-4">
  <div class="col-5"></div>
  <div class="col-3">
    <%= f.submit "新規登録", class:"btn btn-success btn-lg" %>
  </div>
</div>



</div>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="table-active px-3 m-4">商品詳細</h4>
   </div>
</div>
<div class="container-flued">
<div class="row mt-5">
<div class="col-4 ml-5 px-5">
 <p><%= image_tag @item.image, size: "300x250" %></p>
</div>


<div class="col">
<div class="row">
 <div class="col-2">
 商品名
 </div>
 <p class="h5"><%= @item.name %></p>
</div>

<div class="row mt-3">
 <div class="col-2">商品説明</div>
 <p class="h5"><%= @item.introduction %></p>
</div>

<div class="row mt-3">
 <div class="col-2">ジャンル</div>
 <p class="h5"><%= @item.genre.name %></p>
</div>

<div class="row mt-3">
 <div class="col-2">税込価格<br/>
    (税抜価格)</div>
 <p class="h5"><%= "#{(@item.price*1.1).round}(#{@item.price})円" %></p>
</div>

<div class="row mt-3">
  <div class="col-2">販売ステータス</div>

  <% if @item.is_active == true %>
    <p class="lead font-weight-bold text-success">販売中</p>
  <% elsif @item.is_active == false %>
    <p class="lead font-weight-bold text-secondary">販売停止中</p>
  <% end %>

</div>
<div class="row mt-3">
 <div class="col-1"></div>
  <div class="col">
    <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success btn-lg w-25" %>
  </div>
</div>


</div>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
   <div class="row">
      <h4 class="table-active mt-4 px-3">注文履歴詳細</h4>
   </div>
</div>
<div class="container-fluid">
   <div class="row mt-3 ml-5">
      <div class="col-1 mr-5"><h5 class="font-weight-bold">購入者</h5></div>
      <div class="col ml-5"><h5><%= link_to admin_customer_path(@order.customer_id) do %><u class="text-dark"><%= @order.name %></u><% end %></h5></div>
   </div>
   <div class="row mt-1 ml-5">
      <div class="col-1 mr-5"><h5 class="font-weight-bold">注文日</h5></div><div class="col ml-5"><h5><%= @order.created_at.strftime('%Y/%m/%d') %></h5></div>
   </div>
   <div class="row mt-1 ml-5">
      <div class="col-1 mr-5"><h5 class="font-weight-bold">配送先</h5></div><div class="col ml-5"><h5><%= "〒#{@order.postal_code} #{@order.address}" %><br/><%= @order.name %></h5></div>
   </div>
   <div class="row mt-1 ml-5">
      <div class="col-1 mr-5"><h5 class="font-weight-bold">支払方法</h5></div><div class="col ml-5"><h5><%= @order.payment_method_i18n %></h5></div>
   </div>
   <div class="row mt-1 ml-5">
      <div class="col-2"><h5 class="font-weight-bold">注文ステータス</h5></div>
         <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map { |k| [t("enums.order.order_status.#{k}"), k] } %>
            <%= f.submit "更新", class:"btn btn-success btn-sm ml-4" %>
            <% end %>
   </div>



  <div class="row mt-5 ml-5">
    <table class="table col-8 ml-3">
      <thead class="table-active">
        <tr>
          <th class="col-4">商品名</th>
          <th class="col-3">単価（税込）</th>
          <th class="col-2">数量</th>
          <th class="col-3">小計</th>
          <!--<th class="col-3">制作ステータス</th>-->
        </tr>
      </thead>
      <% @order.order_details.each do |order_detail| %>
      <tbody>
        <tr>
          <td class="align-middle"><%= order_detail.item.name %></td>
          <td class="align-middle"><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
          <td class="align-middle"><%= order_detail.quantity %></td>
          <td class="align-middle"><%= (order_detail.item.with_tax_price * order_detail.quantity).to_s(:delimited) %></td>
          <!--<td class="align-middle"><%#= form_with model: @order_detail, url: admin_order_detail_path(@order_detail.item.id), method: :patch do |f| %>-->
          <!--      <%#= f.select :production_status, OrderDetail.production_statuses.keys.map { |k| [t("enums.order_detail.production_status.#{k}"), k] } %>-->
          <!--      <%#= f.submit "更新", class:"btn btn-success btn-sm" %>-->
          <!--      <%# end %>-->
          <!--</td>-->
        </tr>
      </tbody>
      <% end %>
    </table>
    <table class="col-3 ml-5">
       <tr><td class="py-5"></td><td class="py-5"></td></tr>
       <tr><td class="col-6"><h5 class="font-weight-bold">商品合計</h5></td><td class="lead"><%= "#{(@order.amount - 800).to_s(:delimited)}円" %></td></tr>
       <tr><td class="col-6"><h5 class="font-weight-bold">送料</h5></td><td class="lead"><%= "#{@order.postage}円" %></td></tr>
       <tr><td class="col-6"><h5 class="font-weight-bold pb-3">請求金額合計</h5></td><td class="font-weight-bold lead pb-3"><%= "#{(@order.amount).to_s(:delimited)}円" %></td></tr>
    </table>
  </div>
</div>