config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  scope module: :public do#顧客・会員
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/confirm' => 'customers#confirm', as: 'confirm'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    post '/cart_item/:id' => 'cart_items#update', as: 'cart_item'
    delete '/cart_item/:id' => 'cart_items#destroy', as: 'destroy_cart_item'
    delete '/cart_items' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post '/orders/confirm' => 'orders#confirm', as: 'order_confirm'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update, :confirm, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
    resources :orders, only: [:new, :confirm, :complete, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end


  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }




  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  has_one_attached :image


  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { before: 0, confirm: 1, making: 2, before_sending: 3, sent: 4 }
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: {before: 0, waiting: 1, making: 2, finish: 3}

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).per(10)
    @total = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

   private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   protect_from_forgery



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end


end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="footerFixed">
  <header class="border border-dark">
    <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <%= link_to root_path do %>
       <div class="btn btn-outline-dark align-middle px-5"><h2>LOGO</h2></div>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">


        <% if customer_signed_in? %>
        <h6 class="mr-5 pr-5 pt-3"><%= "ようこそ、#{current_customer.last_name}さん！" %></h6>
        <li class="nav-item">
          <%= link_to "マイページ", customer_path(current_customer.id), class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:'btn btn-outline-secondary' %>
        </li>

        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_root_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "ジャンル一覧", admin_genres_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'btn btn-outline-secondary' %>
        </li>



        <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, class:'btn btn-outline-secondary mr-5' %>
        </li>

        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class:'btn btn-outline-secondary' %>
        </li>

        <% end %>

     </ul>
      </div>
    </div>
  </nav>
</header>
<main>
  <%= yield %>
</main>

<footer class="fixed-bottom border border-dark pb-5 pt-2">
  <div class="container-fluid">
  </div>
</footer>
</div>

  </body>
</html>